[package]
name = "oxc-jsx-dom-expressions"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
html-escape = "0.2.13"
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
napi-derive = "2.12.2"
once_cell = "1.20.2"
oxc = { version = "0.34.0", features = ["parser", "semantic", "transformer", "codegen", "sourcemap"] }
oxc_traverse = "0.34.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
